version: '3'

services: 
  web:
    build: .
    working_dir: /src/apps
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload 
    volumes:
      - ./src:/src
    environment:
      - PYTHONPATH=/src
    ports: 
      - "8000:8000"
    restart: on-failure

