from .get_all_ingredients_with_quantities_query.get_all_ingredients_with_quantities_query import GetAllIngredientWithQuantitiesService
from .get_orders_by_menu_query.get_orders_by_menu_query import GetOrdersByMenuService
from .get_total_sales_from_orders_by_dish_query.get_total_sales_from_orders_by_dish_query import GetTtotalSalesFromOrdersByDishService
from .get_frequent_clients_query.get_frequent_clients_query import GetFrequentClientsService
from .get_frequent_dishes_query.get_frequent_dishes_query import GetFrequentDishesService